name: Docker Build and Push

on:
  workflow_call:
    inputs:
      build_args:
        description: 'Arguments passed to docker build'
        required: false
        type: string
      build_file_path:
        description: 'Path to the Dockerfile'
        default: './Dockerfile'
        type: string
      build_context:
        description: 'Build context directory'
        default: '.'
        type: string
      docker_username:
        description: "Docker Hub username"
        required: true
        type: string
      image_name:
        description: "Docker image name"
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_PASSWORD:
        description: 'Docker Hub password'
        required: true

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Git Tag or SHA
        id: vars
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG=${GITHUB_SHA::7}
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ inputs.docker_username }}/${{ inputs.image_name }}:${{ env.IMAGE_TAG }}
            ${{ inputs.docker_username }}/${{ inputs.image_name }}:latest
          push: true
