name: Docker Build and Push
on:
  workflow_call:
    inputs:
      build_args:
        description: 'Arguments passed to docker build'
        required: false
        type: string
      build_file_path:
        description: 'Path to the Dockerfile'
        default: './Dockerfile'
        type: string
      build_context:
        description: 'Build context for Docker'
        default: '.'
        type: string
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
      registry:
        description: 'Docker registry (e.g., docker.io, ghcr.io)'
        default: 'docker.io'
        type: string
      username:
        description: 'Registry username'
        required: true
        type: string
      password:
        description: 'Registry password'
        required: true
        type: string

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.build_file_path }}
          build-args: ${{ inputs.build_args }}
          tags: |
            ${{ inputs.registry }}/${{ inputs.username }}/${{ inputs.image_name }}:latest
            ${{ inputs.registry }}/${{ inputs.username }}/${{ inputs.image_name }}:${{ github.sha }}
          push: true
