name: Docker Build Test
on:
  workflow_call:
    inputs:
      build_args:
        description: 'args passed to docker build'
        required: false
        type: string
      build_file_path:
        description: 'path to a directory containing a Dockerfile, or a specific Dockerfile compatible file'
        default: './Dockerfile'
        type: string
      build_context:
        description: 'path to a directory containing a Dockerfile, or a specific Dockerfile compatible file'
        default: '.'
        type: string
      
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.github_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build the container image
        run: docker build -t my-image:${{ github.sha }} --build-arg BUILD_ARGS=${{ inputs.build_args }} -f ${{ inputs.build_file_path }} ${{ inputs.build_context }}
        shell: bash
